### ISSUE TITLE
scan API failing

### ISSUE THREAD

**Issue by wanxiaoxi** [picatz/shodanz#85]
The client `#scan` method is broken. I suspect Shodan has changed their interface for this API endpoint. It now expects the IP(s) of the scan to be in a flat, non-json string submitted as a POST body. Their example:

```
$ curl -X POST "https://api.shodan.io/shodan/scan?key={YOUR_API_KEY}" -d 'ips=8.8.8.8,1.1.1.1'
```

**Comment by picatz** [comment]
👋 Hello, thank you for reporting this! I also suspect they've changed their API endpoint.

To fix, I think we need to update this part of the code to provide a `body:`, instead of the `ips:` (which is treated as a URL query parameter):
https://github.com/picatz/shodanz/blob/f18520d61711ebf733d7d81d9d67deaba3199463/lib/shodanz/apis/rest.rb#L110-L112

I should be able to get to this later this week, but please feel free to make a PR if you're interested!

**Comment by picatz** [comment]
In order to successfully debug / fix this issue, I need scan credits added to my account. I've reached out to Shodan's support (and @achillean directly) to hopefully get that sorted out.

**Comment by picatz** [comment]
Somewhat related, the related test for this has been passing in CI, but because it has been masking the error:
https://github.com/picatz/shodanz/blob/f18520d61711ebf733d7d81d9d67deaba3199463/spec/rest_api_spec.rb#L15-L25

Removing the `reactor.async do` block reveals the error:
```console
  1) Shodanz::API::REST#scan should be able to scan a host on the internet
     Failure/Error: raise "Got response status #{resp.status}"
     
     RuntimeError:
       Got response status 401
     # ./lib/shodanz/apis/utils.rb:132:in `poster'
     # ./lib/shodanz/apis/utils.rb:178:in `block in async_post'
     # /usr/local/rvm/gems/ruby-3.2.2/gems/async-2.6.5/lib/async/task.rb:160:in `block in run'
     # /usr/local/rvm/gems/ruby-3.2.2/gems/async-2.6.5/lib/async/task.rb:330:in `block in schedule'
```

So, the `reactor.async do` stuff needs to be removed from the tests. I'll do that as part of this fix.

**Comment by wanxiaoxi** [comment]
Hi Kent,

Thanks for the followup! I would love to fix the issue but have too much work work on my plate at the moment. If there is no rush I would be happy to make a PR for this sometime in Dec.

**Comment by picatz** [comment]
No problem at all @wanxiaoxi! Thankfully, @achillean got my API access sorted out super fast, so I plan to tackle this later this week.

So, if you can try to find some time to validate my PR once I have it available, I would really appreciate that!

**Comment by picatz** [comment]
Also thank you to @ioquatix for the thumbs up, I'm going to assume that means the tests look good to you! 😄
